### ISSUE TITLE
Accordion methods

### ISSUE THREAD

**Issue by arthurtyukayev** [guilhermewaess/SemVue#9]
I assume with this implementation you're not adding any of the accordion behaviors? Such as refresh, open(index), close others, close index?

**Comment by guilhermewaess** [comment]
@arthurtyukayev 
It wasn't planned when I started the project, my focus is delivery the basic modules and after all start to work in some improvements.
I see a easy solution if you need to use behaviors (use $ref).
So if you need that feature soon as possible, let me know :)

**Comment by arthurtyukayev** [comment]
I plan on contributing to this project because I use Semantic UI with Vue for some of my projects. So if this will be actively developed, I will certainly write some components and submit pull requests. I just wanted to know what depth you’re working with here.
If the eventual goal is full coverage of each components API then I’ll write the with that in mind.

**Comment by guilhermewaess** [comment]
Well, I think that a full cover of components behaviors is matter of time, I began with this project because use Semantic in my projects became a lot of repetitions of code and the tests are painfull (jquery makes the stuff hard to test). So, I think the priority is other modules, in the other hand, if you need some feature that doesnt exists yet, feel free to implement or request :D 
And most important, feedback's are welcome.

Thanks for your interest on project and feel free to contact-me anytime :D
